extends: eslint:recommended
parser: esprima
parserOptions:
  ecmaVersion: 2015
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
env:
  es6: true
  node: true
  mocha: true
rules:
  brace-style: [ error, 1tbs ]
  indent: [ error, 4 ]
  keyword-spacing: error
  no-var: error
globals:
  expect: true
  assert: true